### ISSUE TITLE
Where's the client for the release

### ISSUE THREAD

**Issue by GhostNaix** [ClashersRepublic/Cerberus#6]
Where's the client apk for the Release ?

**Comment by antzsmt** [comment]
Use 9.256 client

**Comment by GhostNaix** [comment]
@antzsmt How did you get it to work I've patch libg.so with xena and then repacked the 9.256.20 apk but the client crashes as soon as it detects the cerberus

**Comment by antzsmt** [comment]
You can use any 9.256 version client

**Comment by antzsmt** [comment]
Also disable rc4

**Comment by antzsmt** [comment]
I have a newer version git here: https://github.com/antzsmt/ClashLand/

**Comment by GhostNaix** [comment]
rc4 ? How do you disable it in the client?

**Comment by antzsmt** [comment]
Visit my site and you can find a client there http://clashology.ddns.net. btw i dont support this particular repo you are referring to.. checkout github.com/antzsmt/ClashLand/

**Comment by antzsmt** [comment]
And would be easier to chat if you join my discord as well :)
